### ISSUE TITLE
i got error from fetch_yahoo

### ISSUE THREAD

**Issue by wac81** [KIC/pandas-ml-quant#21]
run your notbook code :
```
import matplotlib.pyplot as plt
from pandas_ml_common import Constant
from pandas_ml_utils import FeaturesAndLabels, Model, SkModel
from pandas_ml_utils.ml.data.extraction import extract_with_post_processor
from pandas_ml_quant import pd, np, PostProcessedFeaturesAndLabels

# make experiments reproducable
import torch as t
t.manual_seed(0)
df = pd.fetch_yahoo("QQQ")
```

got error:
```
automatically imported pandas_quant_data_provider 0.2.0
automatically imported pandas_ta_quant_plot 0.2.0
Traceback (most recent call last):
  File "/home/wac/PycharmProjects/pandas-ml-quant/notebooks/features_sel.py", line 67, in <module>
    df = pd.fetch_yahoo("SPY").loc[:'2020-03-17']
  File "/home/wac/anaconda3/envs/myenv/lib/python3.7/site-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'fetch_yahoo'
```

and i try use code like example

```
from pandas_quant_data_provider import pd, YAHOO, INVESTING, CRYPTO_COMPARE

# fetch data from various data sources 
#   * fetches all available dates
#   * caches data for 10 minutes
df = pd.fetch_timeseries({
    YAHOO: ["SPY", "DIA"],
    INVESTING: ["index::NYSE Tick Index::united states", "bond::U.S. 30Y::united states"],
    CRYPTO_COMPARE: ["BTC"]
})

df.tail()
```
i got error no pd

**Comment by wac81** [comment]
What am I supposed to to do?

**Comment by KIC** [comment]
got its own module you need to pip install and then just fetch

`
import pandas_quant_data_provider as qd
df = qd.fetch("SPY")
`
